export type NatureCreation = {
  dateCreation: null | string;
  dateDepotCreation: null | string;
  eirl: boolean;
  entrepriseAgricole: boolean;
  etablieEnFrance: boolean;
  formeJuridique: string;
  indicateurEtablissementFictif: boolean;
  microEntreprise: boolean;
  relieeEntrepriseAgricole: boolean;
  salarieEnFrance: boolean;
  seulsBeneficiairesModifies: null;
  societeEtrangere: boolean;
  typeExploitation: null | string;
};

export type VoletSocial = {
  activiteAnterieureActivite: string | null;
  activiteAnterieureCodeGeo: string | null;
  activiteAnterieureCodePostal: string | null;
  activiteAnterieureCommune: string | null;
  activiteAnterieureDateFin: string | null;
  activiteAnterieurePays: string | null;
  activiteNonSalariee: boolean;
  activiteSimultanee: boolean;
  affiliationPamBiologiste: boolean;
  affiliationPamPharmacien: boolean;
  ancienNumeroSiren: string | null;
  autreActiviteExercee: string | null;
  autreOrganisme: string | null;
  choixOrganismeAssuranceMaladie: string | null;
  dateEffetVoletSocial: string | null;
  declarationMineur: null;
  demandeAcre: boolean;
  departementOrganismeAssuranceMaladie: string | null;
  eirl: boolean;
  entrepriseAgricole: boolean;
  etablieEnFrance: boolean;
  formeJuridique: string | null;
  indicateurActiviteAnterieure: boolean;
  indicateurEtablissementFictif: boolean;
  indicateurRegimeAssuranceMaladie: string | null;
  jeuneAgriculteur: null;
  microEntreprise: boolean;
  mineur: null;
  natureVoletSocial: string | null;
  nbMineursDeclares: null;
  nonSalarieOuConjointBeneficiaireRsaRmi: null;
  organismeAssuranceMaladieActuelle: string | null;
  organismePension: null;
  relieeEntrepriseAgricole: boolean;
  salarieEnFrance: boolean;
  situationVisAVisMsa: string | null;
  societeEtrangere: boolean;
  statutExerciceActiviteSimultanee: string | null;
};

export type PersonDescription = {
  codeInseeGeographique: string;
  codeNationalite: string;
  codePostalNaissance: string;
  confirmRnippMismatch: string | null;
  dateDeNaissance: string;
  dateEffet10P: string | null;
  dateEffet15P: string | null;
  dateEffet17P: string | null;
  dateEffetRoleDeclarant: string | null;
  formeSociale: string | null;
  genre: string;
  indicateurDeNonSedentarite: boolean;
  is10PTriggered: boolean;
  is15PTriggered: boolean;
  is17PTriggered: boolean;
  lieuDeNaissance: string;
  lieuRegistre: string | null;
  mineurEmancipe: string | null;
  nationalite: null | string;
  nicSiege: null | string;
  nom: string;
  nomUsage: string | null;
  numeroSecu: string;
  optionRgpd: string;
  paysNaissance: string;
  prenoms: string[];
  pseudonyme: string | null;
  qualiteDeNonSedentarite: string | null;
  role: string | null;
  siren: null | string;
  situationMatrimoniale: string;
  statutVisAVisFormalite: string | null;
  titre: string | null;
};

export type ContactInfo = {
  dateEffet: string | null;
  mail: string | null;
  optionRgpd: string | null;
  phoneCode: string;
  roleDonneesContact: string | null;
  telecopie: string | null;
  telephone: string;
};

export type Residency = {
  adresse: Partial<Address> | null;
  dateEffet: string | null;
  is28PTriggered: boolean;
  nomResidence: string | null;
  publication: {
    typePublication: string;
    lieuPublication: string;
  } | null;
  residenceInsaisissable: boolean;
  statutPourLaFormalite: string | null;
};

export type Insolvency = {
  residencePrincipale: Residency;
  residencesSecondaires: Residency[] | null;
};

export type Address = {
  caracteristiques: unknown | null;
  codeInseeCommune: string;
  codePays: string;
  codePostal: string;
  commune: string;
  communeAncienne: string | null;
  communeDeRattachement: string | null;
  complementLocalisation: string | null;
  dateEffet16P: string | null;
  datePriseEffetAdresse: string | null;
  distributionSpeciale: string | null;
  empriseAeroport: string | null;
  indicateurValidationBAN: boolean;
  indiceRepetition: string | null;
  indiceRepetitionAutre: string | null;
  is16PTriggered: boolean;
  numVoie: string;
  pays: string | null;
  rgpd: string | null;
  roleAdresse: string | null;
  typeVoie: string;
  voie: string;
  voieCodifiee: string | null;
};

export type BusinessAddress = {
  adresse: Address;
  caracteristiques: {
    ambulant: boolean;
    domiciliataire: boolean;
    indicateurDomicileEntrepreneur: boolean;
    indicateurAdresseEtablissement: boolean;
  };
  dateEffet21P: null | string;
  entrepriseDomiciliataire: null;
  is21PTriggered: boolean;
};

export type Entrepreneur = {
  adresseDomicile: Address;
  capaciteJuridique: null;
  compte: string | null;
  conjoint: null;
  contact: ContactInfo;
  dateEffet35M: string | null;
  dateEffet: string | null;
  descriptionEntrepreneur: string | null;
  descriptionPersonne: PersonDescription;
  greffeImmatriculation: string | null;
  is29Or30PInfoTriggered: boolean;
  is29Or30PTriggered: boolean;
  is35MTriggered: boolean;
  noUniqueIdentification: string | null;
  nouveauRoleConjoint: null;
  regimeMicroSocial: {
    optionMicroSocial: boolean;
    periodiciteVersement: string;
  };
  roleConjoint: null;
  voletSocial: VoletSocial;
};

export type ActivityOrigin = {
  ancienExploitant: unknown | null;
  autreOrigine: unknown | null;
  contrat: unknown | null;
  indicateurPersonneContractanteAncienExploitant: unknown | null;
  publication: unknown | null;
  typeOrigine: string;
};

export type Activity = {
  activiteRattacheeEirl: unknown | null;
  activiteReguliere: unknown | null;
  adresseGerantMandataire: Address | null;
  ancienneAdresse: Address | null;
  autreMotifModification: unknown | null;
  buildings: unknown | null;
  categorisationActivite1: string;
  categorisationActivite2: string;
  categorisationActivite3: string;
  categorisationActivite4: unknown | null;
  codeApe: unknown | null;
  codeAprm: unknown | null;
  dateDebut: string;
  dateDebutPeriode: unknown | null;
  dateEffet20M: unknown | null;
  dateEffet20P: unknown | null;
  dateEffet24Or27PM: unknown | null;
  dateEffet25PActivite: unknown | null;
  dateEffet29PM: unknown | null;
  dateEffet53PMF: unknown | null;
  dateEffet63PMF: unknown | null;
  dateEffet67PM: unknown | null;
  dateEffet: unknown | null;
  dateEffetTransfert: unknown | null;
  dateFin: unknown | null;
  dateFinPeriode: unknown | null;
  denominationEirlRattachee: unknown | null;
  descriptionDetaillee: string;
  destinationActivite: unknown | null;
  destinationActiviteAutre: unknown | null;
  effectifSalarie: unknown | null;
  exerciceActivite: string;
  formeExercice: string;
  identifiantTemporaireEtablissementDestination: unknown | null;
  indicateurActiviteElevage: unknown | null;
  indicateurActiviteOcculte: unknown | null;
  indicateurActiviteViticole: unknown | null;
  indicateurArtisteAuteur: boolean;
  indicateurMarinProfessionnel: boolean;
  indicateurNonSedentaire: boolean;
  indicateurPremiereActivite: unknown | null;
  indicateurPrincipal: boolean;
  indicateurProlongement: boolean;
  is20MTriggered: boolean;
  is20PTriggered: boolean;
  is24Or27PMTriggered: boolean;
  is25PActiviteTriggered: boolean;
  is29PMTriggered: boolean;
  is53PMFTriggered: boolean;
  is61PMFTriggered: boolean;
  is62PMTriggered: boolean;
  is63PMFTriggered: boolean;
  is67PMTriggered: boolean;
  is82PTriggered: boolean;
  jqpa: unknown | null;
  locataireGerantMandataire: unknown | null;
  locationDpb: unknown | null;
  locationGeranceMandat: unknown | null;
  numPraticien: unknown | null;
  origine: ActivityOrigin;
  precisionActivite: string;
  precisionAutre: string;
  precisionAutreCategorie1: unknown | null;
  precisionAutreCategorie2: unknown | null;
  precisionAutreCategorie3: unknown | null;
  precisionAutreCategorie4: unknown | null;
  qualiteNonSedentaire: unknown | null;
  rolePourEtablissement: unknown | null;
  rolePrincipalPourEntreprise: boolean;
  soumissionAuPrecompte: unknown | null;
  statutFormalite: unknown | null;
  statutPraticien: unknown | null;
  surface: unknown | null;
  totalitePartie: unknown | null;
  typpl: unknown | null;
};

export type EstablishmentDescription = {
  activiteNonSedentaire: string | null;
  autonomieJuridique: string | null;
  autreDestination: unknown | null;
  autreIdentifiantEtranger: string | null;
  dateEffet: string | null;
  dateEffetFermeture: string | null;
  dateEffetTransfert: string | null;
  dateFinToutEffectifSalarie: string | null;
  destinationEtablissement: unknown | null;
  enseigne: string | null;
  greffeImmatriculation: string | null;
  identifiantTemporaire: string | null;
  identifiantTemporaireEtablissementDestination: string | null;
  indicateurDomiciliataire: string | null;
  indicateurEtablissementPrincipal: true;
  indicateurEtranger: string | null;
  is60PMFTriggered: false;
  lieuImmatriculation: string | null;
  nomCommercial: string | null;
  nomEtablissement: string | null;
  partnerCenterId: string | null;
  pays: string | null;
  rolePourEntreprise: string | null;
  sansActiviteAutreActiviteSiege: unknown | null;
  siret: string | null;
  statutOuvertFerme: null;
  statutPourFormalite: string | null;
};

export type SalariedWorkforce = {
  dateCessationEmploiSalaries: string | null;
  dateEffet: string | null;
  dateEffetDebutEmploiSalarie: string | null;
  dateEffetFinEmploiSalarie: string | null;
  emploiPremierSalarie: false;
  employeurSalarieNonRegimeFr: unknown | null;
  finEmploiSalarie: unknown | null;
  nombreApprenti: string | number | null;
  nombreSaisonnier: string | number | null;
  nombreSalarie: string | number | null;
  nombreSalariesMarin: string | number | null;
  nombreVrp: string | number | null;
  presenceSalarie: false;
};

export type Etablissement = {
  activites: Activity[];
  adresse: Address;
  adresseDomiciliataire: Address | null;
  adresseGerantMandataire: null;
  dateEffet53PMF: null;
  dateEffetOuvertureEtablissement: null;
  descriptionEtablissement: EstablishmentDescription;
  detailCessationEtablissement: null;
  domiciliataire: unknown | null;
  effectifSalarie: SalariedWorkforce;
  is11PMFTriggered: false;
  is53PMFTriggered: false;
  is54PMFTriggered: false;
  is56PMFTriggered: false;
  is80PMFTriggered: false;
  is82Or83Or84PTriggered: false;
  is84MTriggered: false;
  is84PTriggered: false;
  isLocationGeranceOrGeranceMandat: false;
  isTransfer: false;
  locataireGerantMandataire: null;
  locationGeranceMandat: null;
  nomsDeDomaine: null;
  siegeGerantMandataire: null;
};

export type TaxInfo = {
  aic: unknown | null;
  ali: unknown | null;
  autreOptionFiscale: unknown | null;
  chiffreAffairePrevisionnelService: unknown | null;
  chiffreAffairePrevisionnelVente: unknown | null;
  clienteleAutre: unknown | null;
  clienteleIdentifieesTVA: unknown | null;
  clienteleParticuliers: unknown | null;
  conditionVersementTVA2: unknown | null;
  conditionVersementTVA3: unknown | null;
  conditionVersementTVA: unknown | null;
  dateClotureExerciceComptable: unknown | null;
  dateEffet: unknown | null;
  dateEffetFiscalite: unknown | null;
  dateEnregistrementStatuts: unknown | null;
  detentionParticipationSocieteFrancaise: unknown | null;
  deviseChiffreAffaire: unknown | null;
  immeubles: unknown | null;
  indicateurAutreOptionFiscale: unknown | null;
  indicateurMembreExploitation: unknown | null;
  lic: unknown | null;
  lieuImposition: unknown | null;
  numeroTVAFrance: unknown | null;
  numeroTVAIntra: unknown | null;
  optionParticuliereRegimeBenefice2: unknown | null;
  optionParticuliereRegimeBenefice: unknown | null;
  optionVersementLiberatoire: boolean;
  periodiciteEtOptionsParticulieresTVA2: unknown | null;
  periodiciteEtOptionsParticulieresTVA: unknown | null;
  periodiciteVersement: unknown | null;
  redevablePAS: unknown | null;
  redevableTVA: unknown | null;
  regimeImpositionBenefices2: unknown | null;
  regimeImpositionBenefices: string;
  regimeImpositionTVA2: unknown | null;
  regimeImpositionTVA: string;
  taxeTroisPourcent: unknown | null;
};

export type Identity = {
  adresseCorrespondance: Address;
  contactCorrespondance: string | null;
  contratDAppui: string | null;
  contratDAppuiDeclare: boolean;
  eirl: string | null;
  entrepreneur: Entrepreneur;
  entreprise: string | null;
  insaisissabilite: Insolvency;
  nomCorrespondance: string | null;
  qualiteCorrespondance: string | null;
};

export type PhysicalPerson = {
  adresseEntreprise: BusinessAddress | undefined;
  autresEtablissements: Etablissement[];
  composition: string | null;
  detailCessationEntreprise: unknown | null;
  etablissementPrincipal: null;
  identite: Identity;
  optionsFiscales: TaxInfo;
};

export type Content = {
  declarant: unknown | null;
  evenementCessation: unknown | null;
  exploitation: unknown | null;
  formeExerciceActivitePrincipale: string;
  indicateurActive: unknown | null;
  indicateurPoursuiteCessation: unknown | null;
  isBackToDraft: boolean | null;
  isCreatedViaSimplifiedFormalities: boolean;
  natureCessation: unknown | null;
  natureCreation: NatureCreation;
  personneMorale: unknown | null;
  personnePhysique: PhysicalPerson;
  piecesJointes: null | unknown[];
  succursaleOuFiliale: string;
  tvaIntraCommunautaire: unknown | null;
};

export type EditDraftBody = {
  codeAPE: unknown | null;
  companyName: string;
  content: Content;
  created: string;
  diffusionCommerciale: string;
  diffusionINSEE: unknown | null;
  formalityDraftId?: number;
  formalityScope: any[];
  hasRnippBeenCalled: boolean;
  id: number;
  mandataireId: number;
  nomDossier: string;
  numeroLiasseFormaliteAnterieur: unknown | null;
  observationSignature: unknown | null;
  referenceMandataire: string;
  registreOrigine: unknown | null;
  regularisation: boolean;
  regularizedFormalityId: unknown | null;
  rneContent: unknown | null;
  siren: string | null;
  typeFormalite: string;
  typeLiasse: unknown | null;
  typePersonne: string;
  updated: string;
};
